name: Grade Evaluation Crawler

on:
  workflow_dispatch:
    inputs:
      force_run:
        description: '강제 실행 (월 제한 무시)'
        required: false
        default: false
        type: boolean

jobs:
  collect_grades:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Create data directories
        run: |
          mkdir -p data/grades
      
      - name: Run grade crawler
        run: |
          python src/main.py --grades
        env:
          TZ: Asia/Seoul
      
      - name: Check for changes
        id: verify-changed-files
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "changed=true" >> $GITHUB_OUTPUT
          else
            echo "changed=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push changes
        if: steps.verify-changed-files.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/grades/
          git commit -m "Grade evaluation crawl: $(date +'%Y-%m-%d %H:%M:%S KST')" || exit 0
          git push
      
      - name: Upload data as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: grade-data-${{ github.run_number }}
          path: data/grades/
          retention-days: 30